name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Đăng nhập DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t manhnguyenducvinhyen/ci-cd-app:latest .

      # 4️⃣ Push image lên Docker Hub
      - name: Push Docker image
        run: |
          docker push manhnguyenducvinhyen/ci-cd-app:latest
